### ISSUE TITLE
[Feature request] Allow optional parameters in git source URL for submodule checkout

### ISSUE THREAD

**Issue by jopadan** [pspdev/psp-packages#187]
Which file  changes the  generation of  `hooks/push-to-checkout.sample`?

**Comment by sharkwouter** [comment]
Hey @jopadan, thanks for the report. I don't think we use git submodules, but I'm not sure what the change you are proposing means. Could you clarify further?

**Comment by sharkwouter** [comment]
I'm going to close this one, as it hasn't been updated for a month.
