### ISSUE TITLE
Fix psp-pkg-config --libs output for all libraries

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psp-packages#43]
When using psp-pgk-config with the ``-libs`` flag, it should return all libraries required for linking to work. This is a big problem for the SDL helper libraries for example.

**Comment by sharkwouter** [comment]
SDL2 is only missing SDL2main. SDL2_ttf now has support for setting the libraries in the pc file per platform through CMake, the ones for PSP just need to be added.

In a branch for OceanPop where I'm trying to clean up the CMakeLists.txt file by using pkg-config for the PSP build I still need to add the following dependencies manually for it to work:
```
    if(PSP)
        list(APPEND SDL2_LIBRARIES SDL2main)
        list(APPEND SDL2_MIXER_LIBRARIES vorbisfile vorbis ogg)
        list(APPEND SDL2_IMAGE_LIBRARIES jpeg png z)
        list(APPEND SDL2_TTF_LIBRARIES freetype)
```

For other libraries I do not know what is needed.

**Comment by sharkwouter** [comment]
For sdl2-ttf this is now fixed.

**Comment by diamant3** [comment]
Hello again! Can I try to fix this issue?
