### ISSUE TITLE
Fix paths in pkg-config files

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psp-packages#55]
Currently most pc files either have `/psp` set as prefix (which is broken) or `/__w/psp-packages/psp-packages/bzip2/pkg/bzip2/psp` (works, but not pretty). This should be fixed. Currently only SDL2_mixer.pc has this set correctly. Here is a list of the pc files which require updates:

- [x] bzip2.pc
- [x] dumb.pc
- [x] expat.pc
- [x] freetype2.pc
- [x] jsoncpp.pc
- [x] libconfuse.pc
- [x] libcurl.pc
- [x] libjpeg.pc
- [x] libmikmod.pc
- [x] libpng16.pc
- [x] libpng.pc
- [x] libturbojpeg.pc
- [x] libxmp.pc
- [x] minizip.pc
- [x] ogg.pc
- [x] openal.pc
- [x] pixman-1.pc
- [x] SDL2_gfx.pc
- [x] SDL2_image.pc
- [x] SDL2_mixer.pc
- [x] sdl2.pc
- [x] SDL2_ttf.pc
- [x] SDL_gfx.pc
- [x] SDL_image.pc
- [x] SDL_mixer.pc
- [x] sdl.pc
- [x] SDL_ttf.pc
- [x] sqlite3.pc
- [x] vorbisenc.pc
- [x] vorbisfile.pc
- [x] vorbis.pc

**Comment by diamant3** [comment]
Hello @sharkwouter, Can i help with this issue?

**Comment by sharkwouter** [comment]
@diamant3 sure, that would be appreciated. If you want to know how to do this, take a look at the prepare step in the PSPBUILD of SDL2.

**Comment by diamant3** [comment]
Okay, thanks!

**Comment by sharkwouter** [comment]
Thanks @diamant3 for all the work on this one! It has been completely resolved now!
