### ISSUE TITLE
Understanding psp-pacman to add this server

### ISSUE THREAD

**Issue by godreborn** [pspdev/psp-packages#88]
I have this in my pacman.conf:

[psp-packages]
Server = https://github.com/pspdev/psp-packages

however, I get a 404 error.  I'm very confused on what this is supposed to look like for the psp-packages database.

**Comment by sharkwouter** [comment]
It should be this:
```
[pspdev]
SigLevel = Optional TrustAll
Server = https://github.com/pspdev/psp-packages/releases/latest/download/
```
If you installed psp-pacman, it should already have this repo, though.

**Comment by sharkwouter** [comment]
I'm going to assume that this issue has been resolved now.
